import turtle
turtle.penup()
turtle.setx(-100)
turtle.right(90)
turtle.pendown()
turtle.color("red")
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(100,steps=6)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.goto(-55,-28)
turtle.pendown()
turtle.color("white")
turtle.write("stop",font=("Arial",44,"normal"))
